### ISSUE TITLE
Portage sur React-Native

### ISSUE THREAD

**Issue by Arthuchaut** [CuriosityAR/curiosity#2]
- [x] #3 Intégration de l'API de géolocalisation
- [x] #4 Intégration de la solution de calcul distance Euclidienne
- [x] #5 Intégration de la solution d'orientation sur un plan sphérique
- [x] #6 Intégration de l'UX
